### ISSUE TITLE
手机上，messages左右两边的间距太大

### ISSUE THREAD

**Issue by bigzhu** [bigzhu/follow_center#38]

**Comment by xdliuyong** [comment]
我来认领。

**Comment by sinowisaland** [comment]
我领了

**Comment by bigzhu** [comment]
@sinowisaland 和任务 #42 有关，要你这个先做，我才好改，所以要抓紧了。

**Comment by bigzhu** [comment]
@sinowisaland 

因为
```css
.ui.grid>.row>.column {
  position: relative;
  display: inline-block;
  width: 6.25%;
  padding-left: 1rem;
  padding-right: 1rem;
  vertical-align: top;
}
```
的这个
```css
  padding-left: 1rem;
  padding-right: 1rem;
```
使得两边太宽，为了改任务 https://github.com/bigzhu/lib_bz/issues/1

我可能要先动下这里了
